// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserRegistration.Models;

namespace UserRegistration.Migrations.Course
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserRegistration.Models.CartModel", b =>
                {
                    b.Property<int>("cartid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<double>("cprice");

                    b.Property<string>("ctype")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("cartid");

                    b.ToTable("CartModels");
                });

            modelBuilder.Entity("UserRegistration.Models.CourseModel", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("duration");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<double>("price");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.HasKey("cid");

                    b.ToTable("CourseModels");
                });
#pragma warning restore 612, 618
        }
    }
}
